import hashlib
import logging

from sentence_transformers import SentenceTransformer

from app.core.config import get_settings

logger = logging.getLogger(__name__)


class EmbeddingModel:
    """Service layer wrapper for Sentence Transformers models, handling text-to-vector embeddings."""

    def __init__(self, model: SentenceTransformer, model_name: str) -> None:
        self._model = model
        self._model_name = model_name

    @property
    def model_name(self) -> str:
        return self._model_name

    @property
    def dimension(self) -> int:
        return self._model.get_embedding_dimension()

    @property
    def max_seq_length(self) -> int:
        return self._model.max_seq_length

    def count_tokens(self, text: str) -> int:
        """Counts the number of tokens generated by the model's tokenizer for a given text."""
        return len(
            self._model.tokenizer(
                text,
                truncation=False,
                verbose=False,
            )["input_ids"]
        )

    def encode_documents(
        self,
        texts: list[str],
        batch_size: int = 32,
        normalize: bool = True,
    ) -> list[list[float]]:
        """Encodes a list of article documents into vector embeddings using batch processing."""
        embeddings = self._model.encode_document(
            texts,
            batch_size=batch_size,
            normalize_embeddings=normalize,
            convert_to_numpy=True,
            show_progress_bar=False,
        )
        return embeddings.tolist()

    def encode_query(
        self,
        text: str,
        normalize: bool = True,
    ) -> list[float]:
        """Encodes a single search query string into a vector embedding."""
        embedding = self._model.encode_query(
            text,
            normalize_embeddings=normalize,
            convert_to_numpy=True,
            show_progress_bar=False,
        )
        return embedding.tolist()


def create_embedding_model(model_name: str | None = None) -> EmbeddingModel:
    """Factory function that initializes the embedding model during application lifespan."""
    settings = get_settings()
    name = model_name or settings.embedding_model_name

    logger.info("Loading embedding model: %s", name)
    model = SentenceTransformer(name, device=settings.embedding_device)

    wrapper = EmbeddingModel(model, name)
    logger.info(
        "Model ready — dimension=%d, max_seq_length=%d",
        wrapper.dimension,
        wrapper.max_seq_length,
    )
    return wrapper


def build_embedding_text(title: str, summary: str | None) -> str:
    """Build standardized string representation of an article for embedding calculation."""
    return f"{title}\n\n{summary or ''}".strip()


def compute_content_hash(text: str) -> str:
    """Compute the SHA-256 hex digest of embedding text, used to detect stale vectors."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()